updated main page
psu-libraries/fams_tools pull request #44
Opened 2023-06-27 19:49 UTC by Smullz622

removed gpa and added yearly summary

2023-06-27 20:06 UTC, ajkiessl requested changes
I have one request below.  Also, is the plan to retire the GPA integration entirely? It might be a good idea to remove all of its code; if it will no longer be used.

2023-06-27 20:06 UTC, ajkiessl commented on app/views/main/index.html.erb
> -      <li>Make sure the headers and fields are formatted in the following way:<img src="gpa-headers.png" alt="headers example" width="1100" height="40"></li>
We should remove the `public/gpa-headers.png` file too.

2023-06-27 20:46 UTC, Smullz622 commented
I checked with Nicole, and yes it is retired. I removed all the code related to it with the exception of the schema. I just wanted to double check it was ok to do so before removing the table & related data.

2023-06-28 13:21 UTC, ajkiessl commented
There probably isn't any data being stored for GPA out in production, so it's okay to remove.  I haven't touched this stuff in a while though, so it might be a good idea to double-check on the server.

2023-06-30 14:59 UTC, ajkiessl approved these changes

2023-06-30 15:36 UTC, merged