Updates Dockerfile to prepare for production
psu-libraries/fams_tools pull request #66
Opened 2024-02-16 21:23 UTC by bryanlopezrr

Cleaning up Dockerfile, setting up local_setup script (for local development), modifying docker-compose to include environment variables (these environment variables will need to be configured in the build environment as well in circle ci)

2024-02-19 13:30 UTC, whereismyjetpack requested changes
Thanks for this!

Once these changes are addressed, I'll be able to test locally and provide final feedback. Some of these suggestions are to be more in line with our other apps, others are best practices to reduce layers/size in the resulting image. 

Please ask any questions you might have

2024-02-19 16:08 UTC, whereismyjetpack requested changes

2024-02-19 16:08 UTC, whereismyjetpack commented on Gemfile
> +gem 'simplecov-json', :require => false, :group => :test
if this project isn't setup for codecoverage, remove test reporter from CI, and tackle this as part of another PR

2024-02-21 13:21 UTC, whereismyjetpack requested changes

2024-02-21 13:21 UTC, whereismyjetpack commented on config/credentials.yml.enc
don't push this file up. we can remove it

2024-02-21 13:21 UTC, whereismyjetpack commented on config/environments/production.rb
> +  config.assets.compile = true
for this PR we shouldn't need to change the source code. we can remove this change

2024-02-21 13:21 UTC, whereismyjetpack commented on docker-compose.yml
> +    image: mariadb:10.3
in the future, unrelated changes shouldn't be a part of a PR. this would be a PR titled 'updates dependencies' or something like this

2024-02-21 13:21 UTC, whereismyjetpack commented on Dockerfile
> +ENV SECRET_KEY_BASE=1
I gave guidance on this yesterday. Take a look at how we do this stage in scholarsphere

2024-02-21 15:25 UTC, whereismyjetpack requested changes

2024-02-21 15:25 UTC, whereismyjetpack commented on Gemfile
Can we revert Gemfile and Gemfile.lock with what's presently on `main`? any gem changes can be a separate PR

2024-03-08 14:12 UTC, whereismyjetpack commented
we'll need @ajkiessl  to test locally to make sure it works for him

2024-04-30 18:30 UTC, ajkiessl requested changes
Most of this looks good.  I just added one change request for the db seeding.  Everything seems to be working when I run this locally.  

The QA deployment has some issues, though.  First, the db seed wasn't there so I manually ran that to get the integrations page working.  Second, there are some configurations that aren't being loaded.  We'll have to come up with a strategy for these.  The two configs needed are `activity_insight.yml `and the `integration_passcode.yml`.  The `.circleci` versions of these in source control map out what values we need.  I'm assuming we'll want to use the same strategy the database.yml is using (loading ENV variables).  I can meet to go over these if you want.  Finally, there's a directory that needs added to store the post print files.  I'm getting this error when I go to that page: `Errno::ENOENT (No such file or directory @ dir_initialize - /app/public/post_prints)`.  So, I think that directory just needs added.

I'm assuming the files and database data will be migrated from the old setup to the new setup when we push this to production?

2024-05-10 15:59 UTC, ajkiessl approved these changes
I'd say this is good to go

2024-05-10 16:22 UTC, merged